kafka:
  address: [127.0.0.1:9092]
  topic: XXX-sms-0
  group: XxxSmSGroup
  key: sms
  partition: 0
mysql:
  user_name: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  db: xxx
  charset: utf8mb4
  debug: true
  max_idle_conn: 10
  max_open_conn: 50
  conn_max_lifetime: 30
api:
  url: https://yun.tim.qq.com/v5/tlssmssvr/sendsms
  id: xxxx
  key: xxxxxxxxxxxxx
email:
  smtp:
    host: smtp.163.com
    port: 25
    username: xxxx@163.com
    password: xxxx
  send_config:
    from:
      -
        username: xxxx@163.com
        password: xxxx
      - username: xxxx@163.com
          password: xxxx
    to: [xxxx@xxx.com]
    title: 【XXXXX】